---
vagrant_hostname: tripal2.dev
vagrant_machine_name: tripal2
vagrant_synced_folders: []
vagrant_memory: 4096
drupal_composer_install_dir: "/var/www/html/tripal2"
build_composer_project: false
install_site: false
drupal_major_version: 7
drupal_core_path: "{{ drupal_composer_install_dir }}"
drupal_site_name: "Tripal2"
drupal_mysql_database: tripal2
configure_drush_aliases: false
installed_extras:
  - pgsql

php_enable_apc: false

postgresql_shared_buffers: 16MB

apache_vhosts:
  - servername: "{{ drupal_domain }}"
    documentroot: "{{ drupal_core_path }}"

  - servername: "adminer.{{ vagrant_hostname }}"
    documentroot: "{{ adminer_install_dir }}"

  - servername: "xhprof.{{ vagrant_hostname }}"
    documentroot: "{{ php_xhprof_html_dir }}"

  - servername: "pimpmylog.{{ vagrant_hostname }}"
    documentroot: "{{ pimpmylog_install_dir }}"

  - servername: "{{ vagrant_ip }}"
    serveralias: "dashboard.{{ vagrant_hostname }}"
    documentroot: "{{ dashboard_install_dir }}"
    extra_parameters: |
          DirectoryIndex index.html

apache_mods_enabled:
  - expires.load
  - ssl.load
  - rewrite.load

php_enable_php_fpm: false