---
vagrant_box: geerlingguy/ubuntu1204
php_version: "5.5"
php_packages:
  - "php5=5.5.*"
  - "php5-apcu=4.0.10*"
  - "php5-cli=5.5.*"
  - "php5-common=5.5.*"
  - "php5-curl=5.5.*"
  - "php5-dev=5.5.*"
  - "php5-fpm=5.5.*"
  - "php5-gd=5.5.*"
  - "php5-imap=5.5.*"
  - "libpcre3-dev"
  - "php5-json=1.3.9*"
  - "php5-ldap=5.5.*"
  - "php5-mcrypt=5.5.*"
  - "php-pear=5.5.*"
  - "php5-pgsql=5.5.*"
  - "php5-sqlite=5.5.*"
  - "php5-xmlrpc=5.5.*"
php_conf_paths:
  - /etc/php5/apache2
  - /etc/php5/cli
php_extension_conf_paths:
  - /etc/php5/apache2/conf.d
  - /etc/php5/cli/conf.d
php_mysql_package: "php5-mysql=5.5.*"
postgresql_version: 9.3
extra_packages:
  - sqlite
  - libapache2-mod-php5